### ISSUE TITLE
The requested dns-active24 plugin does not appear to be installed - Rocky9

### ISSUE THREAD

**Issue by VS-ALIXCZ** [jahudka/certbot-dns-active24#11]
Hi all,
I am submitting a new knowledge about error "The requested dns-active24 plugin does not appear to be installed".
Certbot from Python pip must be installed for the dns-active24 plugin to work properly. If certbot from the yum/dnf system package has ever been installed on the machine before, pip will not overwrite it, but will make a new installation in /usr/local/bin/cerbot. However, the subsequent call to #certbot launches the original yum/dnf certbot, which cannot load the plugin. Certbot must be called with the full path /usr/local/bin/certbot certonly -a dns-active24 -d *.domain.bla ... I hope my experience will save someone time.

Tested on Centos 8.6 and Rocky 8x-9

**Comment by jahudka** [comment]
hi, sorry for the looong delay, I've updated the readme to include a warning about compatibility when installing Certbot from the distro package manager, but unfortunately short of releasing and maintaining a version of this package via all the major popular package managers I don't know how to fix this, so I can't do much more..
