### ISSUE TITLE
Where to get dns_active24_api_key and dns_active24_secret ? I have dns_active24_token only 

### ISSUE THREAD

**Issue by tlamik** [jahudka/certbot-dns-active24#14]
I am not able to find these two variables at Active24 web. Could someone kick me to the right way.
Thanks

**Comment by jahudka** [comment]
Hi, these would be the credentials for the new [Active24 REST API v2](https://rest.active24.cz/v2/docs/intro), which they're rolling out gradually - not everyone has access yet. I think you can ask at the Active24 Helpdesk and they'll migrate your account on request; until you get migrated, you can still use the v1.x version of this plugin, which targets the old v1 API and needs just the token.

**Comment by tlamik** [comment]
Hi, by credentials you mean username/password ? I am pretty sure, that out account was migrated a few days ago, but old v1 API still works for me. 
I am trying to setup this plugin in Nginx Proxy Manager and there is a new version which demands API v2. I am not sure if it's possible to downgrade this in NPM.

edit: it turns out that migration of our account has failed and that's why we are still on v1 API ..
edit2: downgraded version of this plugin works nice in NPM

**Comment by jahudka** [comment]
Hi, no, definitely not username / password, don't ever put those in the plugin's config lol 😆 great that you were able to work it out. If you have any issues after your account is migrated and you upgrade to v2, feel free to reach out!
